version: "2.1"

networks:
  public:
    driver_opts:
      encrypted: 1
  shared:
    internal: true
    driver_opts:
      encrypted: 1

services:
  cdnjs_cloudflare_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "cdnjs.cloudflare.com"
    environment:
      TARGET: "cdnjs.cloudflare.com"
      PRE_RESOLVE: 1

  fonts_googleapis_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "fonts.googleapis.com"
    environment:
      TARGET: "fonts.googleapis.com"
      PRE_RESOLVE: 1

  fonts_gstatic_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "fonts.gstatic.com"
    environment:
      TARGET: "fonts.gstatic.com"
      PRE_RESOLVE: 1

  www_google_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "www.google.com"
    environment:
      TARGET: "www.google.com"
      PRE_RESOLVE: 1

  www_gravatar_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "www.gravatar.com"
    environment:
      TARGET: "www.gravatar.com"
      PRE_RESOLVE: 1
  api_github_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "api.github.com"
    environment:
      TARGET: "api.github.com"
      PRE_RESOLVE: 1
  facturacion_itadmin_com_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "facturacion.itadmin.com.mx"
    environment:
      TARGET: "facturacion.itadmin.com.mx"
      PRE_RESOLVE: 1
  pas_telematel_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "pas.telematel.com"
    environment:
      TARGET: "pas.telematel.com"
      PRE_RESOLVE: 1
  services_openerp_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "services.openerp.com"
    environment:
      TARGET: "services.openerp.com"
      PRE_RESOLVE: 1
  openpay_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "openpay.mx"
    environment:
      TARGET: "openpay.mx"
      PRE_RESOLVE: 1
  sat_gob_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "sat.gob.mx"
    environment:
      TARGET: "sat.gob.mx"
      PRE_RESOLVE: 1
  www_sat_gob_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "www.sat.gob.mx"
    environment:
      TARGET: "www.sat.gob.mx"
      PRE_RESOLVE: 1
  demo-facturacion_finkok_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "demo-facturacion.finkok.com"
    environment:
      TARGET: "demo-facturacion.finkok.com"
      PRE_RESOLVE: 1
  solucionfactible_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "solucionfactible.com"
    environment:
      TARGET: "solucionfactible.com"
      PRE_RESOLVE: 1
  facturacion_finkok_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "facturacion.finkok.com"
    environment:
      TARGET: "facturacion.finkok.com"
      PRE_RESOLVE: 1
  sandbox-api_openpay_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "sandbox-api.openpay.mx"
    environment:
      TARGET: "sandbox-api.openpay.mx"
      PRE_RESOLVE: 1
  testing_solucionfactible_com:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "testing.solucionfactible.com"
    environment:
      TARGET: "testing.solucionfactible.com"
      PRE_RESOLVE: 1
  wppsandbox_mit_com_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "wppsandbox.mit.com.mx"
    environment:
      TARGET: "wppsandbox.mit.com.mx"
      PRE_RESOLVE: 1
  sandbox-dashboard_openpay_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "sandbox-dashboard.openpay.mx"
    environment:
      TARGET: "sandbox-dashboard.openpay.mx"
      PRE_RESOLVE: 1
  qa5_mitec_com_mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "qa5.mitec.com.mx"
    environment:
      TARGET: "qa5.mitec.com.mx"
      PRE_RESOLVE: 1
  consultaqr.facturaelectronica.sat.gob.mx:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      public:
      shared:
        aliases:
          - "consultaqr.facturaelectronica.sat.gob.mx"
    environment:
      TARGET: "consultaqr.facturaelectronica.sat.gob.mx"
      PRE_RESOLVE: 1
